site_name: Sun
site_description: 基于FastAPI和gRPC轻量级微服务开发框架
site_url: https://github.com/xqk/sun

theme:
  name: material
  palette:
    - scheme: 'default'
      media: '(prefers-color-scheme: light)'
      toggle:
        icon: 'material/lightbulb'
        name: "Switch to dark mode"
    - scheme: 'slate'
      media: '(prefers-color-scheme: dark)'
      primary: 'blue'
      toggle:
        icon: 'material/lightbulb-outline'
        name: 'Switch to light mode'

repo_name: xqk/sun
repo_url: https://github.com/xqk/sun
edit_uri: ""

nav:
- 简介: index.md
- App: application.md
- 数据库: database.md
- 缓存: cache.md
- 资源: resource.md
- 事件: event.md
- Schema: schema.md
- Utility: utility.md
- 测试: testing.md

markdown_extensions:
  - mkautodoc
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

extra:
  alternate:
    - name: English
      link: /sun/
      lang: en
    - name: 简体中文
      link: /sun/zh/
      lang: zh
